export enum deliveryAddressTypes {
  SET_DELIVERY_ADDRESS = 'SET_DELIVERY_ADDRESS',
  SET_DELIVERY_ADDRESS_SUCCESS = 'SET_DELIVERY_ADDRESS_SUCCESS',
  SET_DELIVERY_ADDRESS_FAILURE = 'SET_DELIVERY_ADDRESS_FAILURE',
}
