export enum basketActionsTypes {
  SET_BASKET_REQUEST = 'SET_BASKET_REQUEST',
  SET_BASKET_SUCCESS = 'SET_BASKET_SUCCESS',
  SET_BASKET_FAILURE = 'SET_BASKET_FAILURE',

  GET_BASKET_REQUEST = 'GET_BASKET_REQUEST',
  GET_BASKET_SUCCESS = 'GET_BASKET_SUCCESS',
  GET_BASKET_FAILURE = 'GET_BASKET_FAILURE',

  ADD_MULTIPLE_PRODUCT_REQUEST = 'ADD_MULTIPLE_PRODUCT_REQUEST',
  ADD_MULTIPLE_PRODUCT_SUCCESS = 'ADD_MULTIPLE_PRODUCT_SUCCESS',
  ADD_MULTIPLE_PRODUCT_FAILURE = 'ADD_MULTIPLE_PRODUCT_FAILURE',

  ADD_PRODUCT_REQUEST = 'ADD_PRODUCT_REQUEST',
  ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS',
  ADD_PRODUCT_FAILURE = 'ADD_PRODUCT_FAILURE',

  REMOVE_PRODUCT_REQUEST = 'REMOVE_PRODUCT_REQUEST',
  REMOVE_PRODUCT_SUCCESS = 'REMOVE_PRODUCT_SUCCESS',
  REMOVE_PRODUCT_FAILURE = 'REMOVE_PRODUCT_FAILURE',

  UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST',
  UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS',
  UPDATE_PRODUCT_FAILURE = 'UPDATE_PRODUCT_FAILURE',

  GET_SINGLE_RESTAURANT_CALENDAR = 'GET_SINGLE_RESTAURANT_CALENDAR',
  GET_SINGLE_RESTAURANT_CALENDAR_SUCCESS = 'GET_SINGLE_RESTAURANT_CALENDAR_SUCCESS',
  GET_SINGLE_RESTAURANT_CALENDAR_FAILURE = 'GET_SINGLE_RESTAURANT_CALENDAR_FAILURE',

  UPDATE_BASKET_TIME_WANTED = 'UPDATE_BASKET_TIME_WANTED',
  UPDATE_BASKET_TIME_WANTED_SUCCESS = 'UPDATE_BASKET_TIME_WANTED_SUCCESS',
  UPDATE_BASKET_TIME_WANTED_FAILURE = 'UPDATE_BASKET_TIME_WANTED_FAILURE',

  DELETE_BASKET_TIME_WANTED = 'DELETE_BASKET_TIME_WANTED',
  DELETE_BASKET_TIME_WANTED_SUCCESS = 'DELETE_BASKET_TIME_WANTED_SUCCESS',
  DELETE_BASKET_TIME_WANTED_FAILURE = 'DELETE_BASKET_TIME_WANTED_FAILURE',

  UPDATE_BASKET_TIP_AMOUNT = 'UPDATE_BASKET_TIP_AMOUNT',
  UPDATE_BASKET_TIP_AMOUNT_SUCCESS = 'UPDATE_BASKET_TIP_AMOUNT_SUCCESS',
  UPDATE_BASKET_TIP_AMOUNT_FAILURE = 'UPDATE_BASKET_TIP_AMOUNT_FAILURE',

  UPDATE_BASKET_COUPON_CODE = 'UPDATE_BASKET_COUPON_CODE',
  UPDATE_BASKET_COUPON_CODE_SUCCESS = 'UPDATE_BASKET_COUPON_CODE_SUCCESS',
  UPDATE_BASKET_COUPON_CODE_FAILURE = 'UPDATE_BASKET_COUPON_CODE_FAILURE',

  VALIDETE_BASKET = 'VALIDETE_BASKET',
  VALIDETE_BASKET_SUCCESS = 'VALIDETE_BASKET_SUCCESS',
  VALIDETE_BASKET_FAILURE = 'VALIDETE_BASKET_FAILURE',

  SUBMIT_BASKET_SINGLE_PAYMENT = 'SUBMIT_BASKET_SINGLE_PAYMENT',
  SUBMIT_BASKET_SINGLE_PAYMENT_SUCCESS = 'SUBMIT_BASKET_SINGLE_PAYMENT_SUCCESS',
  SUBMIT_BASKET_SINGLE_PAYMENT_FAILURE = 'SUBMIT_BASKET_SINGLE_PAYMENT_FAILURE',

  CREATE_BASKET_FROM_PREV = 'CREATE_BASKET_FROM_PREV',
  CREATE_BASKET_FROM_PREV_SUCCESS = 'CREATE_BASKET_FROM_PREV_SUCCESS',
  CREATE_BASKET_FROM_PREV_FAILURE = 'CREATE_BASKET_FROM_PREV_FAILURE',

  CREATE_BASKET_FROM_PREV_ORDER_REQUEST = 'CREATE_BASKET_FROM_PREV_ORDER_REQUEST',
  CREATE_BASKET_FROM_PREV_ORDER_SUCCESS = 'CREATE_BASKET_FROM_PREV_ORDER_SUCCESS',
  CREATE_BASKET_FROM_PREV_ORDER_FAILURE = 'CREATE_BASKET_FROM_PREV_ORDER_FAILURE',

  CREATE_BASKET_FROM_FAV_ORDER_REQUEST = 'CREATE_BASKET_FROM_FAV_ORDER_REQUEST',
  CREATE_BASKET_FROM_FAV_ORDER_SUCCESS = 'CREATE_BASKET_FROM_FAV_ORDER_SUCCESS',
  CREATE_BASKET_FROM_FAV_ORDER_FAILURE = 'CREATE_BASKET_FROM_FAV_ORDER_FAILURE',

  REMOVE_BASKET_ORDER_CONFIRMATION = 'REMOVE_BASKET_ORDER_CONFIRMATION  '
}
