export enum basketActionsTypes {
  GET_DUMMY_BASKET_REQUEST = 'GET_DUMMY_BASKET_REQUEST',
  GET_DUMMY_BASKET_SUCCESS = 'GET_DUMMY_BASKET_SUCCESS',
  GET_DUMMY_BASKET_FAILURE = 'GET_DUMMY_BASKET_FAILURE',

  GET_BASKET_REQUEST = 'GET_BASKET_REQUEST',
  GET_BASKET_SUCCESS = 'GET_BASKET_SUCCESS',
  GET_BASKET_FAILURE = 'GET_BASKET_FAILURE',

  ADD_SINGLE_PRODUCT_REQUEST = 'ADD_SINGLE_PRODUCT_REQUEST',
  ADD_SINGLE_PRODUCT_SUCCESS = 'ADD_SINGLE_PRODUCT_SUCCESS',
  ADD_SINGLE_PRODUCT_FAILURE = 'ADD_SINGLE_PRODUCT_FAILURE',

  GET_SINGLE_RESTAURANT_CALENDAR = 'GET_SINGLE_RESTAURANT_CALENDAR',
  GET_SINGLE_RESTAURANT_CALENDAR_SUCCESS = 'GET_SINGLE_RESTAURANT_CALENDAR_SUCCESS',
  GET_SINGLE_RESTAURANT_CALENDAR_FAILURE = 'GET_SINGLE_RESTAURANT_CALENDAR_FAILURE',

  UPDATE_BASKET_TIME_WANTED = "UPDATE_BASKET_TIME_WANTED",
  UPDATE_BASKET_TIME_WANTED_SUCCESS = "UPDATE_BASKET_TIME_WANTED_SUCCESS",
  UPDATE_BASKET_TIME_WANTED_FAILURE = "UPDATE_BASKET_TIME_WANTED_FAILURE",


  DELETE_BASKET_TIME_WANTED = "DELETE_BASKET_TIME_WANTED",
  DELETE_BASKET_TIME_WANTED_SUCCESS = "DELETE_BASKET_TIME_WANTED_SUCCESS",
  DELETE_BASKET_TIME_WANTED_FAILURE = "DELETE_BASKET_TIME_WANTED_FAILURE",

  UPDATE_BASKET_TIP_AMOUNT = 'UPDATE_BASKET_TIP_AMOUNT',
  UPDATE_BASKET_TIP_AMOUNT_SUCCESS = 'UPDATE_BASKET_TIP_AMOUNT_SUCCESS',
  UPDATE_BASKET_TIP_AMOUNT_FAILURE = 'UPDATE_BASKET_TIP_AMOUNT_FAILURE'
}
