export enum restaurantActionsTypes {
  GET_RESTAURANT_INFO_REQUEST = 'GET_RESTAURANT_INFO_REQUEST',
  GET_RESTAURANT_INFO_SUCCESS = 'GET_RESTAURANT_INFO_SUCCESS',
  GET_RESTAURANT_INFO_FAILURE = 'GET_RESTAURANT_INFO_FAILURE',
}
