export enum restaurantActionsTypes {
  GET_RESTAURANT_INFO_REQUEST = 'GET_RESTAURANT_INFO_REQUEST',
  GET_RESTAURANT_INFO_SUCCESS = 'GET_RESTAURANT_INFO_SUCCESS',
  GET_RESTAURANT_INFO_FAILURE = 'GET_RESTAURANT_INFO_FAILURE',

  SET_RESTAURANT_INFO_REQUEST = 'SET_RESTAURANT_INFO_REQUEST',
  SET_RESTAURANT_INFO_SUCCESS = 'SET_RESTAURANT_INFO_SUCCESS',
  SET_RESTAURANT_INFO_FAILURE = 'SET_RESTAURANT_INFO_FAILURE',

  SET_RESTAURANT_INFO_ORDER_TYPE = 'SET_RESTAURANT_INFO_ORDER_TYPE',
  RESTAURANT_RESET_REQUEST = 'RESTAURANT_RESET_REQUEST',
  SET_RESTAURANT_SESSION_REQUEST = 'SET_RESTAURANT_SESSION_REQUEST',
  SET_SESSION_REQUEST = 'SET_SESSION_REQUEST',

  SET_PROMOTIONAL_MSG = 'SET_PROMOTIONAL_MSG',
}
