export enum facebookConversionTypes {
  FACEBOOK_PURCHASE_EVENT = 'FACEBOOK_PURCHASE_EVENT',
  FACEBOOK_ADD_CART_EVENT = 'FACEBOOK_ADD_CART_EVENT',

  FACEBOOK_EVENT_REQUEST = 'FACEBOOK_EVENT_REQUEST',
  FACEBOOK_EVENT_SUCCESS = 'FACEBOOK_EVENT_SUCCESS',
  FACEBOOK_EVENT_FAILURE = 'FACEBOOK_EVENT_FAILURE',
}
