openapi: 3.0.1
info:
  title: Olo Webhooks
  version: '1.0'
  description:
    $ref: webhooks-description-10.md
x-webhooks:
  $ref: webhooks-events-10.yaml
paths: {}
components:
  schemas:
    $ref: webhooks-schemas-10.yaml
tags:
  - name: testEvents
    x-displayName: Test Events
  - name: menuEvents
    x-displayName: Menu Events
  - name: orderEvents
    x-displayName: Order Events
  - name: userEvents
    x-displayName: User Events
  - name: vendorEvents
    x-displayName: Restaurant Events
x-tagGroups:
  - name: Event Types
    description: The following events can be configured to trigger webhook calls.
    tags:
      - testEvents
      - menuEvents
      - orderEvents
      - userEvents
      - vendorEvents