openapi: 3.0.1
info:
  title: Olo Ordering API
  version: "1.1"
  description: 
    $ref: ordering-description-11.md
servers:
- url: https://ordering.api.olosandbox.com/v1.1/
  description: Sandbox
- url: https://ordering.api.olo.com/v1.1/
  description: Production
paths:
  $ref: ordering-paths-11.yaml
components:
  schemas: 
     $ref: ordering-schemas-11.yaml
tags: 
  - name: retrieveConfiguration
    x-displayName: Retrieve Configuration
  - name: retrieveCalendarsDisclaimers
    x-displayName: Retrieve Calendars & Disclaimers
  - name: retrieveMenuProducts
    x-displayName: Retrieve Menu Products
  - name: retrieveProductModifiers
    x-displayName: Retrieve Product Modifiers
  - name: creationRetrievalGroupOrdering
    x-displayName: Creation, Retrieval, & Group Ordering
  - name: productsAddUpdateUpsell
    x-displayName: "Products: Add, Update, & Upsell"
  - name: tipCouponLoyaltyRewards
    x-displayName: Tip, Coupon, & Loyalty Rewards
  - name: handoffDeliveryDispatch
    x-displayName: Handoff, Delivery, & Dispatch
  - name: timeWantedManualFire
    x-displayName: Time Wanted (& Manual Fire)
  - name: customFields
    x-displayName: Custom Fields & Donations
  - name: transfers
    x-displayName: Transfers
  - name: billingOptions
    x-displayName: Billing Options
  - name: validationSubmission
    x-displayName: Validation & Submission
  - name: modificationRetrievalDeliveryStatus
    x-displayName: Modification, Retrieval, & Delivery Status
  - name: manualFire
    x-displayName: Manual Fire
  - name: customerArrival
    x-displayName: Customer Arrival
  - name: creationAuthentication
    x-displayName: Creation & Authentication
  - name: modificationDeletionRetrieval
    x-displayName: Modification, Deletion, & Retrieval
  - name: contactInformation
    x-displayName: Contact Information
  - name: billingInformation
    x-displayName: Billing Information
  - name: favoritesBasketsLocations
    x-displayName: Favorites (Baskets & Locations)
  - name: recentOpenOrdersManualFire
    x-displayName: Recent & Open Orders (Manual Fire)
  - name: loyaltyRewards
    x-displayName: Loyalty Rewards
  - name: unauthorized
    x-displayName: Unauthorized
  - name: vendorExport
    x-displayName: Vendor Export
  - name: orderExport
    x-displayName: Order Export
  - name: feedback
    x-displayName: Feedback
x-tagGroups:
  - name: 'API Reference'
    tags: []
  - name: Restaurant
    tags:
      - retrieveConfiguration
      - retrieveCalendarsDisclaimers
      - retrieveMenuProducts
  - name: Product
    tags:
      - retrieveProductModifiers
  - name: Basket
    tags:
      - creationRetrievalGroupOrdering
      - productsAddUpdateUpsell
      - tipCouponLoyaltyRewards
      - handoffDeliveryDispatch
      - timeWantedManualFire
      - customFields
      - transfers
      - billingOptions
      - validationSubmission
  - name: Order
    tags:
      - modificationRetrievalDeliveryStatus
      - manualFire
      - customerArrival
  - name: User
    tags:
      - creationAuthentication
      - modificationDeletionRetrieval
      - contactInformation
      - billingInformation
      - favoritesBasketsLocations
      - recentOpenOrdersManualFire
      - loyaltyRewards
      - unauthorized
  - name: Export
    tags:
      - vendorExport
      - orderExport
  - name: Feedback
    tags:
      - feedback