export enum favRestaurantActionsTypes {
    GET_SINGLE_RESTAURANT = 'GET_SINGLE_RESTAURANT',
    GET_SINGLE_RESTAURANT_SUCCESS = 'GET_SINGLE_RESTAURANT_SUCCESS',
    GET_SINGLE_RESTAURANT_FAILURE = 'GET_SINGLE_RESTAURANT_FAILURE',
  }
  