export enum userTypes {
  GET_USER_PROFILE = 'GET_USER_PROFILE',
  GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS',
  GET_USER_PROFILE_FAILURE = 'GET_USER_PROFILE_FAILURE',

  GET_USER_RECENT_ORDERS = 'GET_USER_RECENT_ORDERS',
  GET_USER_RECENT_ORDERS_SUCCESS = 'GET_USER_RECENT_ORDERS_SUCCESS',
  GET_USER_RECENT_ORDERS_FAILURE = 'GET_USER_RECENT_ORDERS_FAILURE',

  GET_USER_FAVORITE_ORDERS = 'GET_USER_FAVORITE_ORDERS',
  GET_USER_FAVORITE_ORDERS_SUCCESS = 'GET_USER_FAVORITE_ORDERS_SUCCESS',
  GET_USER_FAVORITE_ORDERS_FAILURE = 'GET_USER_FAVORITE_ORDERS_FAILURE',

  GET_USER_DELIVERY_ADDRESSES = 'GET_USER_DELIVERY_ADDRESSES',
  GET_USER_DELIVERY_ADDRESSES_SUCCESS = 'GET_USER_DELIVERY_ADDRESSES_SUCCESS',
  GET_USER_DELIVERY_ADDRESSES_FAILURE = 'GET_USER_DELIVERY_ADDRESSES_FAILURE',

  SET_USER_DEFAULT_DELIVERY_ADDRESS = 'SET_USER_DEFAULT_DELIVERY_ADDRESS',
  SET_USER_DEFAULT_DEL_ADD_FAILURE = 'SET_USER_DEFAULT_DEL_ADD_FAILURE',
  SET_USER_DEF_DEL_ADD_SUCCESS = 'SET_USER_DEF_DEL_ADD_SUCCESS',

  DELETE_USER_DELIVERY_ADDRESS = 'DELETE_USER_DELIVERY_ADDRESS',
  DEL_USER_DEL_ADD_SUCCESS = 'DEL_USER_DEL_ADD_SUCCESS',
  DEL_USER_DEL_ADD_FAILURE = 'DEL_USER_DEL_ADD_FAILURE',

}
