export enum userTypes {
  GET_USER_PROFILE = 'GET_USER_PROFILE',
  GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS',
  GET_USER_PROFILE_FAILURE = 'GET_USER_PROFILE_FAILURE',

  GET_USER_RECENT_ORDERS = 'GET_USER_RECENT_ORDERS',
  GET_USER_RECENT_ORDERS_SUCCESS = 'GET_USER_RECENT_ORDERS_SUCCESS',
  GET_USER_RECENT_ORDERS_FAILURE = 'GET_USER_RECENT_ORDERS_FAILURE',
}
